controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # RW controllers declaration
    rw_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    rw_effort_controller:
      type: forward_command_controller/ForwardCommandController

    # Arm controllers declaration
    ## Dual arm controllers
    dual_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    dual_arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    dual_arm_effort_controller:
      type: forward_command_controller/ForwardCommandController

    ## Lest arm
    left_arm_position_controller:
      type: forward_command_controller/ForwardCommandController
      
    left_arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    left_arm_effort_controller:
      type: forward_command_controller/ForwardCommandController

    ## Right arm
    right_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    right_arm_effort_controller:
      type: forward_command_controller/ForwardCommandController

# RW controllers configuration
rw_velocity_controller:
  ros__parameters:
    joints: 
    - rw_joint
    interface_name: velocity

rw_effort_controller:
  ros__parameters:
    joints: 
    - rw_joint
    interface_name: effort

# Arm controllers configuration
## Dual arm controllers
dual_arm_position_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: position

dual_arm_velocity_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: velocity

dual_arm_effort_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: effort

## Lest arm
fts_broadcaster:
  ros__parameters:
    sensor_name: leptrino_fts
    frame_id: tool_link

left_arm_position_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: position

left_arm_velocity_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: velocity

left_arm_effort_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
    interface_name: effort

## Right arm
right_arm_position_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: position

right_arm_velocity_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: velocity

right_arm_effort_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_elbow_joint
    interface_name: effort